#define PORTD *(unsigned char*) 0x2B
#define DDRD  *(unsigned char*) 0x2A
#define PIND  *(unsigned char*) 0x29
#define PORTC *(unsigned char*) 0x28
#define DDRC  *(unsigned char*) 0x27
#define PINC  *(unsigned char*) 0x26
#define PORTB *(unsigned char*) 0x25
#define DDRB  *(unsigned char*) 0x24
#define PINB  *(unsigned char*) 0x23